// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:twn_square/environments.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Environment.webAppKey,
    appId: '1:1088144608378:web:c494063dbc32e94e633fc3',
    messagingSenderId: '1088144608378',
    projectId: 'twnsquare-3b8ab',
    authDomain: 'twnsquare-3b8ab.firebaseapp.com',
    storageBucket: 'twnsquare-3b8ab.firebasestorage.app',
    measurementId: 'G-TG2WSXBNNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Environment.androidAppKey,
    appId: '1:1088144608378:android:8fd93b6c14e105f8633fc3',
    messagingSenderId: '1088144608378',
    projectId: 'twnsquare-3b8ab',
    storageBucket: 'twnsquare-3b8ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Environment.iosAppKey,
    appId: '1:1088144608378:ios:4edbb42d23444aa6633fc3',
    messagingSenderId: '1088144608378',
    projectId: 'twnsquare-3b8ab',
    storageBucket: 'twnsquare-3b8ab.firebasestorage.app',
    iosBundleId: 'com.example.twnSquare',
  );

}